name: Run Tests

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox wget tar curl

          GECKO_VERSION="v0.34.0"
          echo "Installing geckodriver version $GECKO_VERSION"
          
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          rm geckodriver-$GECKO_VERSION-linux64.tar.gz

          echo "Finding Firefox executable..."
          which firefox
          ls -la /usr/bin/firefox*
          ls -la /usr/lib/firefox*
          ls -la /snap/bin/firefox 2>/dev/null || echo "No snap firefox"
          
          geckodriver --version
          firefox --version

          FIREFOX_PATH=$(which firefox)
          echo "FIREFOX_PATH=$FIREFOX_PATH" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: |
          pytest -v tests/

